export const GRADING_SYSTEMS = {
  "UGC Bangladesh": {
    name: "UGC Standard Grading System (Bangladesh)",
    scale: "4.0",
    country: "Bangladesh",
    grades: [
      { range: "80-100", label: "A+", value: 4.0 },
      { range: "75-79", label: "A", value: 3.75 },
      { range: "70-74", label: "A-", value: 3.5 },
      { range: "65-69", label: "B+", value: 3.25 },
      { range: "60-64", label: "B", value: 3.0 },
      { range: "55-59", label: "B-", value: 2.75 },
      { range: "50-54", label: "C+", value: 2.5 },
      { range: "45-49", label: "C", value: 2.25 },
      { range: "40-44", label: "D", value: 2.0 },
      { range: "Below 40", label: "F", value: 0.0 },
    ],
  },
  BRACU: {
    name: "BRAC University Grading System",
    scale: "4.0",
    country: "Bangladesh",
    grades: [
      { range: "97-100", label: "A+", value: 4.0 },
      { range: "90-96", label: "A", value: 4.0 },
      { range: "85-89", label: "A-", value: 3.7 },
      { range: "80-84", label: "B+", value: 3.3 },
      { range: "75-79", label: "B", value: 3.0 },
      { range: "70-74", label: "B-", value: 2.7 },
      { range: "65-69", label: "C+", value: 2.3 },
      { range: "60-64", label: "C", value: 2.0 },
      { range: "57-59", label: "C-", value: 1.7 },
      { range: "55-56", label: "D+", value: 1.3 },
      { range: "52-54", label: "D", value: 1.0 },
      { range: "Below 52", label: "F", value: 0.0 },
    ],
  },
  NSU: {
    name: "North South University Grading System",
    scale: "4.0",
    country: "Bangladesh",
    grades: [
      { range: "93-100", label: "A", value: 4.0 },
      { range: "90-92", label: "A-", value: 3.7 },
      { range: "87-89", label: "B+", value: 3.3 },
      { range: "83-86", label: "B", value: 3.0 },
      { range: "80-82", label: "B-", value: 2.7 },
      { range: "77-79", label: "C+", value: 2.3 },
      { range: "73-76", label: "C", value: 2.0 },
      { range: "70-72", label: "C-", value: 1.7 },
      { range: "67-69", label: "D+", value: 1.3 },
      { range: "60-66", label: "D", value: 1.0 },
      { range: "Below 60", label: "F", value: 0.0 },
    ],
  },
  UIU: {
    name: "United International University Grading System",
    scale: "4.0",
    country: "Bangladesh",
    grades: [
      { range: "90-100", label: "A", value: 4.0 },
      { range: "86-89", label: "A-", value: 3.67 },
      { range: "82-85", label: "B+", value: 3.33 },
      { range: "78-81", label: "B", value: 3.0 },
      { range: "74-77", label: "B-", value: 2.67 },
      { range: "70-73", label: "C+", value: 2.33 },
      { range: "66-69", label: "C", value: 2.0 },
      { range: "62-65", label: "C-", value: 1.67 },
      { range: "58-61", label: "D+", value: 1.33 },
      { range: "55-57", label: "D", value: 1.0 },
      { range: "Below 55", label: "F", value: 0.0 },
    ],
  },
  IUB: {
    name: "Independent University, Bangladesh Grading System",
    scale: "4.0",
    country: "Bangladesh",
    grades: [
      { range: "90-100", label: "A", value: 4.0 },
      { range: "85-89", label: "A-", value: 3.7 },
      { range: "80-84", label: "B+", value: 3.3 },
      { range: "75-79", label: "B", value: 3.0 },
      { range: "70-74", label: "B-", value: 2.7 },
      { range: "65-69", label: "C+", value: 2.3 },
      { range: "60-64", label: "C", value: 2.0 },
      { range: "55-59", label: "C-", value: 1.7 },
      { range: "50-54", label: "D+", value: 1.3 },
      { range: "45-49", label: "D", value: 1.0 },
      { range: "Below 45", label: "F", value: 0.0 },
    ],
  },
  SRM: {
    name: "SRM Institute of Science and Technology Grading System",
    scale: "10.0",
    country: "India",
    grades: [
      { range: "91-100", label: "O", value: 10.0 },
      { range: "81-90", label: "A+", value: 9.0 },
      { range: "71-80", label: "A", value: 8.0 },
      { range: "61-70", label: "B+", value: 7.0 },
      { range: "56-60", label: "B", value: 6.0 },
      { range: "50-55", label: "C", value: 5.0 },
      { range: "Below 50", label: "F", value: 0.0 },
    ],
  },
  VIT: {
    name: "Vellore Institute of Technology Grading System",
    scale: "10.0",
    country: "India",
    grades: [
      { range: "90-100", label: "S", value: 10.0 },
      { range: "80-89", label: "A", value: 9.0 },
      { range: "70-79", label: "B", value: 8.0 },
      { range: "60-69", label: "C", value: 7.0 },
      { range: "55-59", label: "D", value: 6.0 },
      { range: "50-54", label: "E", value: 5.0 },
      { range: "Below 50", label: "F", value: 0.0 },
    ],
  },
  "KTU Kerala": {
    name: "APJ Abdul Kalam Technological University Grading System",
    scale: "10.0",
    country: "India",
    grades: [
      { range: "90-100", label: "S", value: 10.0 },
      { range: "85-89", label: "A+", value: 9.0 },
      { range: "80-84", label: "A", value: 8.5 },
      { range: "75-79", label: "B+", value: 8.0 },
      { range: "70-74", label: "B", value: 7.0 },
      { range: "65-69", label: "C", value: 6.0 },
      { range: "60-64", label: "P", value: 5.0 },
      { range: "Below 60", label: "F", value: 0.0 },
    ],
  },
  Saveetha: {
    name: "Saveetha Institute of Medical and Technical Sciences Grading System",
    scale: "10.0",
    country: "India",
    grades: [
      { range: "91-100", label: "O", value: 10.0 },
      { range: "81-90", label: "A+", value: 9.0 },
      { range: "71-80", label: "A", value: 8.0 },
      { range: "61-70", label: "B+", value: 7.0 },
      { range: "50-60", label: "B", value: 6.0 },
      { range: "Below 50", label: "RA", value: 0.0 },
    ],
  },
  "GGSIPU IPU": {
    name: "Guru Gobind Singh Indraprastha University Grading System",
    scale: "10.0",
    country: "India",
    grades: [
      { range: "90-100", label: "O", value: 10.0 },
      { range: "75-89", label: "A+", value: 9.0 },
      { range: "65-74", label: "A", value: 8.0 },
      { range: "55-64", label: "B+", value: 7.0 },
      { range: "50-54", label: "B", value: 6.0 },
      { range: "45-49", label: "C", value: 5.0 },
      { range: "40-44", label: "P", value: 4.0 },
      { range: "Below 40", label: "F", value: 0.0 },
    ],
  },
  "10.0 Scale (India)": {
    name: "10-Point Grading Scale (India)",
    scale: "10.0",
    country: "India",
    grades: [
      { range: "90-100", label: "O", value: 10.0 },
      { range: "80-89", label: "A+", value: 9.0 },
      { range: "70-79", label: "A", value: 8.0 },
      { range: "60-69", label: "B+", value: 7.0 },
      { range: "50-59", label: "B", value: 6.0 },
      { range: "40-49", label: "C", value: 5.0 },
      { range: "Below 40", label: "F", value: 0.0 },
    ],
  },
  "5.0 Scale": {
    name: "5.0 GPA Scale",
    scale: "5.0",
    country: "International",
    grades: [
      { range: "90-100", label: "A+", value: 5.0 },
      { range: "80-89", label: "A", value: 4.0 },
      { range: "70-79", label: "B", value: 3.0 },
      { range: "60-69", label: "C", value: 2.0 },
      { range: "50-59", label: "D", value: 1.0 },
      { range: "Below 50", label: "F", value: 0.0 },
    ],
  },
  UAF: {
    name: "University of Agriculture Faisalabad Grading System",
    scale: "4.0",
    country: "Pakistan",
    grades: [
      { range: "80-100", label: "A", value: 4.0 },
      { range: "65-79", label: "B", value: 3.0 },
      { range: "50-64", label: "C", value: 2.0 },
      { range: "40-49", label: "D", value: 1.0 },
      { range: "Below 40", label: "F", value: 0.0 },
    ],
  },
  COMSATS: {
    name: "COMSATS University Islamabad Grading System",
    scale: "4.0",
    country: "Pakistan",
    grades: [
      { range: "90-100", label: "A", value: 4.0 },
      { range: "85-89", label: "A-", value: 3.7 },
      { range: "80-84", label: "B+", value: 3.3 },
      { range: "75-79", label: "B", value: 3.0 },
      { range: "70-74", label: "B-", value: 2.7 },
      { range: "65-69", label: "C+", value: 2.3 },
      { range: "60-64", label: "C", value: 2.0 },
      { range: "50-59", label: "D", value: 1.0 },
      { range: "Below 50", label: "F", value: 0.0 },
    ],
  },
  "UCP Lahore": {
    name: "University of Central Punjab Grading System",
    scale: "4.0",
    country: "Pakistan",
    grades: [
      { range: "90-100", label: "A", value: 4.0 },
      { range: "86-89", label: "A-", value: 3.67 },
      { range: "81-85", label: "B+", value: 3.33 },
      { range: "77-80", label: "B", value: 3.0 },
      { range: "72-76", label: "B-", value: 2.67 },
      { range: "68-71", label: "C+", value: 2.33 },
      { range: "63-67", label: "C", value: 2.0 },
      { range: "58-62", label: "C-", value: 1.67 },
      { range: "54-57", label: "D+", value: 1.33 },
      { range: "50-53", label: "D", value: 1.0 },
      { range: "Below 50", label: "F", value: 0.0 },
    ],
  },
  "UMT Lahore": {
    name: "University of Management and Technology Grading System",
    scale: "4.0",
    country: "Pakistan",
    grades: [
      { range: "85-100", label: "A", value: 4.0 },
      { range: "80-84", label: "A-", value: 3.7 },
      { range: "75-79", label: "B+", value: 3.3 },
      { range: "70-74", label: "B", value: 3.0 },
      { range: "65-69", label: "B-", value: 2.7 },
      { range: "61-64", label: "C+", value: 2.3 },
      { range: "58-60", label: "C", value: 2.0 },
      { range: "55-57", label: "C-", value: 1.7 },
      { range: "50-54", label: "D", value: 1.0 },
      { range: "Below 50", label: "F", value: 0.0 },
    ],
  },
  "Punjab University": {
    name: "University of the Punjab Grading System",
    scale: "4.0",
    country: "Pakistan",
    grades: [
      { range: "85-100", label: "A", value: 4.0 },
      { range: "80-84", label: "A-", value: 3.7 },
      { range: "75-79", label: "B+", value: 3.3 },
      { range: "70-74", label: "B", value: 3.0 },
      { range: "65-69", label: "B-", value: 2.7 },
      { range: "61-64", label: "C+", value: 2.3 },
      { range: "58-60", label: "C", value: 2.0 },
      { range: "55-57", label: "C-", value: 1.7 },
      { range: "50-54", label: "D", value: 1.0 },
      { range: "Below 50", label: "F", value: 0.0 },
    ],
  },
  "HEC Pakistan": {
    name: "HEC Pakistan Grading Scale",
    scale: "4.0",
    country: "Pakistan",
    grades: [
      { range: "90-100", label: "A", value: 4.0 },
      { range: "85-89", label: "A-", value: 3.7 },
      { range: "80-84", label: "B+", value: 3.3 },
      { range: "75-79", label: "B", value: 3.0 },
      { range: "71-74", label: "B-", value: 2.7 },
      { range: "68-70", label: "C+", value: 2.3 },
      { range: "64-67", label: "C", value: 2.0 },
      { range: "60-63", label: "C-", value: 1.7 },
      { range: "57-59", label: "D+", value: 1.3 },
      { range: "53-56", label: "D", value: 1.0 },
      { range: "45-52", label: "D-", value: 0.7 },
      { range: "Below 45", label: "F", value: 0.0 },
    ],
  },
  "UK Honours": {
    name: "UK Degree Classification (Honours)",
    scale: "Class",
    country: "United Kingdom",
    grades: [
      { range: "70-100", label: "First Class (1st)", value: 4.0 },
      { range: "60-69", label: "Upper Second (2:1)", value: 3.3 },
      { range: "50-59", label: "Lower Second (2:2)", value: 2.7 },
      { range: "40-49", label: "Third Class (3rd)", value: 2.0 },
      { range: "Below 40", label: "Fail", value: 0.0 },
    ],
  },
  "US 4.0 Scale": {
    name: "US Standard 4.0 GPA Scale",
    scale: "4.0",
    country: "United States",
    grades: [
      { range: "93-100", label: "A", value: 4.0 },
      { range: "90-92", label: "A-", value: 3.7 },
      { range: "87-89", label: "B+", value: 3.3 },
      { range: "83-86", label: "B", value: 3.0 },
      { range: "80-82", label: "B-", value: 2.7 },
      { range: "77-79", label: "C+", value: 2.3 },
      { range: "73-76", label: "C", value: 2.0 },
      { range: "70-72", label: "C-", value: 1.7 },
      { range: "67-69", label: "D+", value: 1.3 },
      { range: "63-66", label: "D", value: 1.0 },
      { range: "Below 63", label: "F", value: 0.0 },
    ],
  },
  "ECTS Europe": {
    name: "ECTS Grading Scale (European)",
    scale: "ECTS",
    country: "Europe",
    grades: [
      { range: "90-100", label: "A (Excellent)", value: 4.0 },
      { range: "80-89", label: "B (Very Good)", value: 3.5 },
      { range: "70-79", label: "C (Good)", value: 3.0 },
      { range: "60-69", label: "D (Satisfactory)", value: 2.5 },
      { range: "50-59", label: "E (Sufficient)", value: 2.0 },
      { range: "Below 50", label: "F (Fail)", value: 0.0 },
    ],
  },
  "German Scale": {
    name: "German University Grading (1.0–5.0)",
    scale: "1.0–5.0",
    country: "Germany",
    grades: [
      { range: "1.0-1.5", label: "Sehr gut (1.x)", value: 4.0 },
      { range: "1.6-2.5", label: "Gut (2.x)", value: 3.3 },
      { range: "2.6-3.5", label: "Befriedigend (3.x)", value: 2.7 },
      { range: "3.6-4.0", label: "Ausreichend (4.x)", value: 2.0 },
      { range: "Above 4.0", label: "Nicht bestanden", value: 0.0 },
    ],
  },
  "Malaysia IPTA": {
    name: "Malaysian Public University Grading (IPTA 4.0)",
    scale: "4.0",
    country: "Malaysia",
    grades: [
      { range: "80-100", label: "A", value: 4.0 },
      { range: "75-79", label: "A-", value: 3.67 },
      { range: "70-74", label: "B+", value: 3.33 },
      { range: "65-69", label: "B", value: 3.0 },
      { range: "60-64", label: "B-", value: 2.67 },
      { range: "55-59", label: "C+", value: 2.33 },
      { range: "50-54", label: "C", value: 2.0 },
      { range: "45-49", label: "C-", value: 1.67 },
      { range: "40-44", label: "D", value: 1.0 },
      { range: "Below 40", label: "F", value: 0.0 },
    ],
  },
  "UTAR Malaysia": {
    name: "UTAR Grading System (Malaysia)",
    scale: "4.0",
    country: "Malaysia",
    grades: [
      { range: "80-100", label: "A", value: 4.0 },
      { range: "75-79", label: "A-", value: 3.7 },
      { range: "70-74", label: "B+", value: 3.3 },
      { range: "65-69", label: "B", value: 3.0 },
      { range: "60-64", label: "B-", value: 2.7 },
      { range: "55-59", label: "C+", value: 2.3 },
      { range: "50-54", label: "C", value: 2.0 },
      { range: "45-49", label: "D", value: 1.0 },
      { range: "Below 45", label: "F", value: 0.0 },
    ],
  },
  "STPM Malaysia": {
    name: "STPM Grading Scale (Malaysia Pre-University)",
    scale: "4.0",
    country: "Malaysia",
    grades: [
      { range: "90-100", label: "A", value: 4.0 },
      { range: "80-89", label: "A-", value: 3.67 },
      { range: "70-79", label: "B+", value: 3.33 },
      { range: "60-69", label: "B", value: 3.0 },
      { range: "50-59", label: "B-", value: 2.67 },
      { range: "40-49", label: "C+", value: 2.33 },
      { range: "30-39", label: "C", value: 2.0 },
      { range: "20-29", label: "D", value: 1.0 },
      { range: "Below 20", label: "F", value: 0.0 },
    ],
  },
};

export function getMaxGradePoint(systemKey) {
  const system = GRADING_SYSTEMS[systemKey];
  if (!system) return "4.00";
  return system.grades[0].value.toFixed(2);
}

export function getCalculatorLink(systemKey) {
  return `/?system=${encodeURIComponent(systemKey)}#calculator`;
}
