import { GRADING_SYSTEMS, getCalculatorLink } from './gradingSystems';

export const UNIVERSITIES = [
  // Bangladesh
  {
    slug: 'university-of-dhaka',
    name: 'University of Dhaka',
    shortName: 'DU',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    featured: true,
    desc: 'Bangladesh\'s oldest public university. Most faculties follow the standard UGC 4.0 grading scale.',
  },
  {
    slug: 'buet',
    name: 'Bangladesh University of Engineering and Technology',
    shortName: 'BUET',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    featured: true,
    desc: 'The country\'s top engineering school. Uses the UGC standard scale with strict pass marks.',
  },
  {
    slug: 'jahangirnagar-university',
    name: 'Jahangirnagar University',
    shortName: 'JU',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    desc: 'A leading public university near Dhaka, following the national UGC grading policy.',
  },
  {
    slug: 'rajshahi-university',
    name: 'Rajshahi University',
    shortName: 'RU',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    desc: 'One of the largest public universities in northern Bangladesh on the standard UGC scale.',
  },
  {
    slug: 'chittagong-university',
    name: 'University of Chittagong',
    shortName: 'CU',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    desc: 'Major public university in Chattogram using the UGC-mandated 4.0 grading system.',
  },
  {
    slug: 'brac-university',
    name: 'BRAC University',
    shortName: 'BRACU',
    country: 'Bangladesh',
    type: 'Private',
    system: 'BRACU',
    featured: true,
    desc: 'Top private university with its own detailed 12-grade point structure — different from UGC.',
  },
  {
    slug: 'north-south-university',
    name: 'North South University',
    shortName: 'NSU',
    country: 'Bangladesh',
    type: 'Private',
    system: 'NSU',
    featured: true,
    desc: 'Bangladesh\'s first private university. Uses a distinct grading scale with tighter mark bands.',
  },
  {
    slug: 'uiu',
    name: 'United International University',
    shortName: 'UIU',
    country: 'Bangladesh',
    type: 'Private',
    system: 'UIU',
    desc: 'Private university in Dhaka with a custom 4.0 scale and fine-grained grade intervals.',
  },
  {
    slug: 'iub',
    name: 'Independent University, Bangladesh',
    shortName: 'IUB',
    country: 'Bangladesh',
    type: 'Private',
    system: 'IUB',
    desc: 'Well-known private institution in Dhaka with its own published grading table.',
  },
  {
    slug: 'east-west-university',
    name: 'East West University',
    shortName: 'EWU',
    country: 'Bangladesh',
    type: 'Private',
    system: 'UGC Bangladesh',
    desc: 'Private university in Dhaka. Most programs align with the UGC standard grading scale.',
  },
  {
    slug: 'ruet',
    name: 'Rajshahi University of Engineering & Technology',
    shortName: 'RUET',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    desc: 'Leading public engineering university in Rajshahi on the standard UGC 4.0 grading scale.',
  },
  {
    slug: 'kuet',
    name: 'Khulna University of Engineering & Technology',
    shortName: 'KUET',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    desc: 'Premier engineering institution in Khulna using UGC-mandated grade point values.',
  },
  {
    slug: 'sust',
    name: 'Shahjalal University of Science and Technology',
    shortName: 'SUST',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    desc: 'Top science and technology university in Sylhet following the national UGC grading policy.',
  },
  {
    slug: 'national-university-bangladesh',
    name: 'National University of Bangladesh',
    shortName: 'NU',
    country: 'Bangladesh',
    type: 'Public',
    system: 'UGC Bangladesh',
    desc: 'Bangladesh\'s largest affiliating university — millions of college students use the UGC standard scale.',
  },
  {
    slug: 'iit-delhi',
    name: 'Indian Institute of Technology Delhi',
    shortName: 'IIT Delhi',
    country: 'India',
    type: 'Public',
    system: '10.0 Scale (India)',
    featured: true,
    desc: 'Premier IIT using the common 10-point absolute grading scale used across most IITs.',
  },
  {
    slug: 'iit-bombay',
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    country: 'India',
    type: 'Public',
    system: '10.0 Scale (India)',
    desc: 'Top-ranked IIT with a 10.0 CGPA scale. Grades like O, A+, and A map to 10, 9, and 8 points.',
  },
  {
    slug: 'iit-madras',
    name: 'Indian Institute of Technology Madras',
    shortName: 'IIT Madras',
    country: 'India',
    type: 'Public',
    system: '10.0 Scale (India)',
    desc: 'Leading southern IIT following the standard 10-point grading system.',
  },
  {
    slug: 'srm-university',
    name: 'SRM Institute of Science and Technology',
    shortName: 'SRM',
    country: 'India',
    type: 'Private',
    system: 'SRM',
    desc: 'Large private deemed university in Chennai with its own 10-point O/A+/A grade structure.',
  },
  {
    slug: 'vit-vellore',
    name: 'Vellore Institute of Technology',
    shortName: 'VIT',
    country: 'India',
    type: 'Private',
    system: 'VIT',
    desc: 'Major private university using S/A/B/C/D/E/F letter grades on a 10-point scale.',
  },
  {
    slug: 'ktu-kerala',
    name: 'APJ Abdul Kalam Technological University',
    shortName: 'KTU',
    country: 'India',
    type: 'Public',
    system: 'KTU Kerala',
    desc: 'Kerala\'s state technical university with S, A+, A, B+, B, C, P, and F grades.',
  },
  {
    slug: 'anna-university',
    name: 'Anna University',
    shortName: 'Anna',
    country: 'India',
    type: 'Public',
    system: '10.0 Scale (India)',
    desc: 'Tamil Nadu\'s flagship technical university. Affiliated colleges mostly use the 10-point scale.',
  },
  {
    slug: 'vtu-karnataka',
    name: 'Visvesvaraya Technological University',
    shortName: 'VTU',
    country: 'India',
    type: 'Public',
    system: '10.0 Scale (India)',
    desc: 'Karnataka\'s state technical university governing hundreds of engineering colleges.',
  },
  {
    slug: 'ggsipu',
    name: 'Guru Gobind Singh Indraprastha University',
    shortName: 'GGSIPU',
    country: 'India',
    type: 'Public',
    system: 'GGSIPU IPU',
    desc: 'Delhi state university with O, A+, A, B+, B, C, P, and F on a 10-point scale.',
  },
  {
    slug: 'saveetha-university',
    name: 'Saveetha Institute of Medical and Technical Sciences',
    shortName: 'Saveetha',
    country: 'India',
    type: 'Private',
    system: 'Saveetha',
    desc: 'Chennai-based institute with O/A+/A/B+/B grades and a unique RA grade for re-appear.',
  },
  {
    slug: 'mumbai-university',
    name: 'University of Mumbai',
    shortName: 'MU',
    country: 'India',
    type: 'Public',
    system: '10.0 Scale (India)',
    desc: 'One of India\'s oldest universities. Most modern programs use the 10-point CGPA system.',
  },
  {
    slug: 'delhi-university',
    name: 'University of Delhi',
    shortName: 'DU',
    country: 'India',
    type: 'Public',
    system: '10.0 Scale (India)',
    desc: 'Central university with thousands of affiliated colleges on the 10-point grading scale.',
  },

  // Pakistan
  {
    slug: 'nust',
    name: 'National University of Sciences and Technology',
    shortName: 'NUST',
    country: 'Pakistan',
    type: 'Public',
    system: 'HEC Pakistan',
    featured: true,
    desc: 'Pakistan\'s top-ranked engineering university following the HEC standard 4.0 scale.',
  },
  {
    slug: 'lums',
    name: 'Lahore University of Management Sciences',
    shortName: 'LUMS',
    country: 'Pakistan',
    type: 'Private',
    system: 'HEC Pakistan',
    desc: 'Premier private research university using the HEC-mandated grading framework.',
  },
  {
    slug: 'comsats-islamabad',
    name: 'COMSATS University Islamabad',
    shortName: 'COMSATS',
    country: 'Pakistan',
    type: 'Public',
    system: 'COMSATS',
    desc: 'Multi-campus public university with a detailed A through F grading table.',
  },
  {
    slug: 'fast-nu',
    name: 'FAST-NUCES',
    shortName: 'FAST',
    country: 'Pakistan',
    type: 'Private',
    system: 'HEC Pakistan',
    desc: 'Leading CS and engineering university aligned with HEC Pakistan grading guidelines.',
  },
  {
    slug: 'qaau',
    name: 'Quaid-i-Azam University',
    shortName: 'QAU',
    country: 'Pakistan',
    type: 'Public',
    system: 'HEC Pakistan',
    desc: 'Islamabad\'s top public research university on the standard HEC 4.0 scale.',
  },
  {
    slug: 'punjab-university',
    name: 'University of the Punjab',
    shortName: 'PU',
    country: 'Pakistan',
    type: 'Public',
    system: 'Punjab University',
    desc: 'Pakistan\'s oldest university with its own published grade point table.',
  },
  {
    slug: 'ucp-lahore',
    name: 'University of Central Punjab',
    shortName: 'UCP',
    country: 'Pakistan',
    type: 'Private',
    system: 'UCP Lahore',
    desc: 'Private Lahore university with a comprehensive 11-level grading structure.',
  },
  {
    slug: 'umt-lahore',
    name: 'University of Management and Technology',
    shortName: 'UMT',
    country: 'Pakistan',
    type: 'Private',
    system: 'UMT Lahore',
    desc: 'Lahore-based private university with its own grade bands from A to F.',
  },
  {
    slug: 'uaf-faisalabad',
    name: 'University of Agriculture, Faisalabad',
    shortName: 'UAF',
    country: 'Pakistan',
    type: 'Public',
    system: 'UAF',
    desc: 'Major agricultural university using a simplified A/B/C/D/F five-grade system.',
  },
  {
    slug: 'air-university',
    name: 'Air University Islamabad',
    shortName: 'AU',
    country: 'Pakistan',
    type: 'Public',
    system: 'HEC Pakistan',
    desc: 'HEC-recognized university for aviation and engineering programs.',
  },

  // United Kingdom
  {
    slug: 'university-of-oxford',
    name: 'University of Oxford',
    shortName: 'Oxford',
    country: 'United Kingdom',
    type: 'Public',
    system: 'UK Honours',
    featured: true,
    region: 'UK & Europe',
    desc: 'World-leading university using the UK honours classification — First, 2:1, 2:2, and Third.',
  },
  {
    slug: 'university-of-cambridge',
    name: 'University of Cambridge',
    shortName: 'Cambridge',
    country: 'United Kingdom',
    type: 'Public',
    system: 'UK Honours',
    featured: true,
    region: 'UK & Europe',
    desc: 'Elite UK institution where final degree class is based on weighted exam and coursework averages.',
  },
  {
    slug: 'imperial-college-london',
    name: 'Imperial College London',
    shortName: 'Imperial',
    country: 'United Kingdom',
    type: 'Public',
    system: 'UK Honours',
    region: 'UK & Europe',
    desc: 'Top STEM university in London using standard UK honours degree classification bands.',
  },
  {
    slug: 'ucl',
    name: 'University College London',
    shortName: 'UCL',
    country: 'United Kingdom',
    type: 'Public',
    system: 'UK Honours',
    region: 'UK & Europe',
    desc: 'Major London Russell Group university on the UK percentage-to-classification system.',
  },
  {
    slug: 'university-of-manchester',
    name: 'University of Manchester',
    shortName: 'UoM',
    country: 'United Kingdom',
    type: 'Public',
    system: 'UK Honours',
    region: 'UK & Europe',
    desc: 'One of the UK\'s largest universities with transparent honours classification boundaries.',
  },
  {
    slug: 'university-of-edinburgh',
    name: 'University of Edinburgh',
    shortName: 'Edinburgh',
    country: 'United Kingdom',
    type: 'Public',
    system: 'UK Honours',
    region: 'UK & Europe',
    desc: 'Scotland\'s ancient university using UK-wide honours class standards for undergraduate degrees.',
  },
  {
    slug: 'kings-college-london',
    name: "King's College London",
    shortName: 'KCL',
    country: 'United Kingdom',
    type: 'Public',
    system: 'UK Honours',
    region: 'UK & Europe',
    desc: 'Central London Russell Group university with First / 2:1 / 2:2 / Third classifications.',
  },

  // Germany
  {
    slug: 'tu-munich',
    name: 'Technical University of Munich',
    shortName: 'TUM',
    country: 'Germany',
    type: 'Public',
    system: 'German Scale',
    featured: true,
    region: 'UK & Europe',
    desc: 'Germany\'s top technical university using the 1.0 (best) to 5.0 (fail) grading scale.',
  },
  {
    slug: 'lmu-munich',
    name: 'Ludwig Maximilian University of Munich',
    shortName: 'LMU',
    country: 'Germany',
    type: 'Public',
    system: 'German Scale',
    region: 'UK & Europe',
    desc: 'Leading research university in Munich on the standard German numeric grading system.',
  },
  {
    slug: 'heidelberg-university',
    name: 'Heidelberg University',
    shortName: 'Heidelberg',
    country: 'Germany',
    type: 'Public',
    system: 'German Scale',
    region: 'UK & Europe',
    desc: 'Germany\'s oldest university with Sehr gut / Gut / Befriedigend grade bands.',
  },

  // France & Netherlands
  {
    slug: 'sorbonne-university',
    name: 'Sorbonne University',
    shortName: 'Sorbonne',
    country: 'France',
    type: 'Public',
    system: 'ECTS Europe',
    region: 'UK & Europe',
    desc: 'Prestigious Paris university aligned with the European ECTS credit and grading framework.',
  },
  {
    slug: 'tu-delft',
    name: 'Delft University of Technology',
    shortName: 'TU Delft',
    country: 'Netherlands',
    type: 'Public',
    system: 'ECTS Europe',
    region: 'UK & Europe',
    desc: 'Netherlands\' top engineering school using ECTS grades from A (excellent) to F (fail).',
  },
  {
    slug: 'university-of-amsterdam',
    name: 'University of Amsterdam',
    shortName: 'UvA',
    country: 'Netherlands',
    type: 'Public',
    system: 'ECTS Europe',
    region: 'UK & Europe',
    desc: 'Major Dutch research university on the standard European ECTS grading scale.',
  },
  {
    slug: 'trinity-college-dublin',
    name: 'Trinity College Dublin',
    shortName: 'TCD',
    country: 'Ireland',
    type: 'Public',
    system: 'ECTS Europe',
    region: 'UK & Europe',
    desc: 'Ireland\'s top university using ECTS-compatible grading for international mobility.',
  },

  // Malaysia — Semrush easy wins (KD 5–13%)
  {
    slug: 'utm',
    name: 'Universiti Teknologi Malaysia',
    shortName: 'UTM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    featured: true,
    region: 'Malaysia',
    desc: 'Malaysia\'s top technical university. Calculate CGPA using the standard IPTA 4.0 grading scale.',
  },
  {
    slug: 'uitm',
    name: 'Universiti Teknologi MARA',
    shortName: 'UiTM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    featured: true,
    region: 'Malaysia',
    desc: 'Largest public university in Malaysia. Uses the IPTA 4.0 scale for semester GPA and cumulative CGPA.',
  },
  {
    slug: 'utar',
    name: 'Universiti Tunku Abdul Rahman',
    shortName: 'UTAR',
    country: 'Malaysia',
    type: 'Private',
    system: 'UTAR Malaysia',
    featured: true,
    region: 'Malaysia',
    desc: 'Major private university with its own published grade boundaries on a 4.0 CGPA scale.',
  },
  {
    slug: 'upm',
    name: 'Universiti Putra Malaysia',
    shortName: 'UPM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    region: 'Malaysia',
    desc: 'Research university in Serdang using the Malaysian IPTA standard grading system.',
  },
  {
    slug: 'universiti-malaya',
    name: 'Universiti Malaya',
    shortName: 'UM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    featured: true,
    region: 'Malaysia',
    desc: 'Malaysia\'s oldest university. CGPA calculated on the national IPTA 4.0 grade point scale.',
  },
  {
    slug: 'usm',
    name: 'Universiti Sains Malaysia',
    shortName: 'USM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    region: 'Malaysia',
    desc: 'APEX university in Penang on the standard Malaysian public university grading scale.',
  },
  {
    slug: 'utem',
    name: 'Universiti Teknikal Malaysia Melaka',
    shortName: 'UTeM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    region: 'Malaysia',
    desc: 'Technical university in Melaka using IPTA 4.0 grade points for CGPA calculation.',
  },
  {
    slug: 'uthm',
    name: 'Universiti Tun Hussein Onn Malaysia',
    shortName: 'UTHM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    region: 'Malaysia',
    desc: 'Engineering-focused public university in Johor on the IPTA grading scale.',
  },
  {
    slug: 'iium',
    name: 'International Islamic University Malaysia',
    shortName: 'IIUM',
    country: 'Malaysia',
    type: 'Public',
    system: 'Malaysia IPTA',
    region: 'Malaysia',
    desc: 'International Islamic university with IPTA-standard 4.0 CGPA calculation.',
  },
  {
    slug: 'monash-university-malaysia',
    name: 'Monash University Malaysia',
    shortName: 'Monash MY',
    country: 'Malaysia',
    type: 'Private',
    system: 'Malaysia IPTA',
    region: 'Malaysia',
    desc: 'Australian branch campus in Malaysia using a 4.0 CGPA scale aligned with local standards.',
  },
  {
    slug: 'stpm-malaysia',
    name: 'STPM (Malaysia Pre-University)',
    shortName: 'STPM',
    country: 'Malaysia',
    type: 'Pre-University',
    system: 'STPM Malaysia',
    featured: true,
    region: 'Malaysia',
    desc: 'Calculate STPM CGPA for Malaysian pre-university students using the official STPM grade point scale.',
  },
];

export const COUNTRIES = [
  'All',
  'Bangladesh',
  'India',
  'Pakistan',
  'Malaysia',
  'United Kingdom',
  'Germany',
  'France',
  'Netherlands',
  'Ireland',
];

export const UK_EUROPE_COUNTRIES = [
  'United Kingdom',
  'Germany',
  'France',
  'Netherlands',
  'Ireland',
];

export function getUkEuropeUniversities() {
  return UNIVERSITIES.filter((u) => UK_EUROPE_COUNTRIES.includes(u.country));
}

export function getFeaturedUniversities() {
  return UNIVERSITIES.filter((u) => u.featured);
}

export function getUniversitiesByCountry(country) {
  if (country === 'All') return UNIVERSITIES;
  return UNIVERSITIES.filter((u) => u.country === country);
}

export function getUniversityBySlug(slug) {
  return UNIVERSITIES.find((u) => u.slug === slug) ?? null;
}

export function getUniversityCalculatorLink(slug) {
  return `/calculator/${slug}`;
}

export function getUniversityMeta(uni) {
  const system = GRADING_SYSTEMS[uni.system];
  return {
    scale: system?.scale ?? '—',
    systemName: system?.name ?? uni.system,
    calculatorLink: getUniversityCalculatorLink(uni.slug),
  };
}

export { getCalculatorLink };
